package com.ak.api.reporting;

import java.util.concurrent.ConcurrentHashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

/**
 * TestNG listener that prints per-test banner lines to the console. Auto-
 * generated by ra_converter and wired into every emitted TestNG suite XML.
 * Safe to hand-edit; the converter never overwrites this file after the
 * first run (uses File.exists() check upstream).
 *
 * <p>Output shape:
 * <pre>
 *   [TEST] STARTED  &lt;class&gt;#&lt;method&gt;  (thread=pool-1-thread-3)
 *   [TEST] PASSED   &lt;class&gt;#&lt;method&gt;  (Nms)
 *   [TEST] FAILED   &lt;class&gt;#&lt;method&gt;  (Nms) -- &lt;exception message&gt;
 *   [TEST] SKIPPED  &lt;class&gt;#&lt;method&gt;  (Nms)
 * </pre>
 * </p>
 *
 * <p>Complements the STARTED/FINISHED lines embedded inside test method
 * bodies -- those show sequential progress within one thread; this
 * listener shows the framework-level lifecycle across threads.</p>
 */
public class ProgressLogListener implements ITestListener {

    private static final Logger LOG = LoggerFactory.getLogger(ProgressLogListener.class);
    private static final ConcurrentHashMap<String, Long> STARTS = new ConcurrentHashMap<>();
    // Per-method attempt counter: keyed by class#method (no hashcode).
    // Increments on every onTestStart; a terminal PASSED/FAILED clears
    // the entry. RetryAnalyzer-driven retries share the same key so we
    // can suppress intermediate STARTED lines and annotate the terminal
    // outcome with "[after N attempts]".
    private static final ConcurrentHashMap<String, java.util.concurrent.atomic.AtomicInteger> ATTEMPTS
        = new ConcurrentHashMap<>();

    private String key(ITestResult r) {
        return r.getTestClass().getRealClass().getSimpleName()
                + "#" + r.getMethod().getMethodName() + "@" + r.hashCode();
    }

    /**
     * Per-INVOCATION key. Includes a hash of the data-provider parameters
     * so different CSV rows of the same @Test method own different
     * attempt counters. Without the params hash, `[attempt N]` inflated
     * with every row for data-driven tests -- a method with 20 rows
     * showed `[attempt 20]` on the last row even though no retry ever
     * happened. Only true retries (RetryAnalyzer re-invoking with the
     * same params) share a counter now.
     */
    private String methodKey(ITestResult r) {
        return r.getTestClass().getRealClass().getName()
                + "#" + r.getMethod().getMethodName()
                + "@" + java.util.Arrays.deepHashCode(r.getParameters());
    }

    private String label(ITestResult r) {
        return r.getTestClass().getRealClass().getSimpleName()
                + "#" + r.getMethod().getMethodName();
    }

    private long elapsedMs(ITestResult r) {
        Long start = STARTS.remove(key(r));
        if (start == null) return -1L;
        return System.currentTimeMillis() - start;
    }

    private int currentAttempt(ITestResult r) {
        java.util.concurrent.atomic.AtomicInteger c = ATTEMPTS.get(methodKey(r));
        return c == null ? 1 : c.get();
    }

    private void clearAttempts(ITestResult r) {
        ATTEMPTS.remove(methodKey(r));
    }

    // Simple approach: log STARTED once EVER per (class, method) --
    // never clear the seen-set. Multi-row data-driven methods thus show
    // ONE STARTED line + N terminal outcomes (one per row). Retries
    // don't re-log STARTED because the key is already seen. Cleaner and
    // resistant to TestNG's flaky wasRetried() semantics.
    private static final java.util.Set<String> STARTED_LOGGED =
        java.util.Collections.newSetFromMap(new ConcurrentHashMap<>());

    /** Started-set key = class+method only (no params). One STARTED banner
     *  per @Test method for the WHOLE run, regardless of rows / retries. */
    private String startedKey(ITestResult r) {
        return r.getTestClass().getRealClass().getName()
                + "#" + r.getMethod().getMethodName();
    }

    @Override
    public void onTestStart(ITestResult r) {
        STARTS.put(key(r), System.currentTimeMillis());
        ATTEMPTS.computeIfAbsent(methodKey(r),
                k -> new java.util.concurrent.atomic.AtomicInteger(0))
                .incrementAndGet();
        if (STARTED_LOGGED.add(startedKey(r))) {
            LOG.info("[TEST] STARTED  {}  (thread={})",
                    label(r), Thread.currentThread().getName());
        }
    }

    @Override
    public void onTestSuccess(ITestResult r) {
        int attempt = currentAttempt(r);
        if (attempt > 1) {
            LOG.info("[TEST] PASSED   {}  ({}ms) [attempt {}]",
                    label(r), elapsedMs(r), attempt);
        } else {
            LOG.info("[TEST] PASSED   {}  ({}ms)", label(r), elapsedMs(r));
        }
    }

    @Override
    public void onTestFailure(ITestResult r) {
        int attempt = currentAttempt(r);
        Throwable t = r.getThrowable();
        String msg = (t == null) ? "(no throwable)" : t.getClass().getSimpleName()
                + ": " + (t.getMessage() == null ? "" : t.getMessage());
        // Log every FAILED at WARN with attempt count. Users see the
        // retry story in the [Retry] lines RetryAnalyzer prints AND in
        // the attempt=N here. Silencing intermediate failures based on
        // wasRetried() is unreliable in TestNG (see prior bug), so we
        // log all failures and let the reader spot the pattern.
        LOG.warn("[TEST] FAILED   {}  ({}ms) [attempt {}] -- {}",
                label(r), elapsedMs(r), attempt, msg);
    }

    @Override
    public void onTestSkipped(ITestResult r) {
        int attempt = currentAttempt(r);
        // Skips triggered by RetryAnalyzer's failure-then-retry cycle
        // show 0ms elapsed. Suppress those; the surrounding [Retry] and
        // FAILED lines already tell the story.
        long elapsed = elapsedMs(r);
        if (elapsed < 5) {
            return;
        }
        LOG.info("[TEST] SKIPPED  {}  ({}ms) [attempt {}]",
                label(r), elapsed, attempt);
    }

    @Override
    public void onStart(ITestContext context) {
        // Reset per-<test> state so a long-lived JVM (Surefire fork reuse
        // across two <test> blocks, or `mvn -Dtest=Foo test surefire:test`
        // rerun in the same fork) starts fresh: STARTED banners re-fire
        // per <test> block, and stale attempt counters from a prior block
        // don't leak into the new one's [attempt N] annotations.
        STARTED_LOGGED.clear();
        ATTEMPTS.clear();
        STARTS.clear();
        LOG.info("[TEST] ==== SUITE START: {} (thread-count={}) ====",
                context.getName(), context.getSuite().getXmlSuite().getThreadCount());
    }

    @Override
    public void onFinish(ITestContext context) {
        LOG.info("[TEST] ==== SUITE FINISH: {}  passed={}, failed={}, skipped={} ====",
                context.getName(),
                context.getPassedTests().size(),
                context.getFailedTests().size(),
                context.getSkippedTests().size());
    }
}
