package com.ak.api.reporting;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

/**
 * Auto-generated by ra_converter. Writes a SMALL, shareable failure digest.
 *
 * <p>A full regression log is tens of MB -- too big to attach, and the
 * interesting part is a handful of distinct causes repeated hundreds of
 * times. This listener writes target/failure-digest.txt: failures
 * GROUPED by signature, counts first, a few example test-case ids each.
 * Typically a few KB.</p>
 *
 * <p>Retries are collapsed. The retry analyzer runs a failing method up to
 * 3 times, so a raw log shows each failure three times; the digest keys on
 * class#method#test_case_id and keeps one entry.</p>
 *
 * <p>The signature is the assertion/exception text with volatile parts
 * masked -- ids, emails, domains, uuids, timestamps -- so the same defect
 * across 60 rows collapses to one line instead of 60.</p>
 */
public class FailureDigestListener implements ITestListener {

    private static final Map<String, String[]> FAILURES = new LinkedHashMap<>();

    private static final Map<String, Integer> AUTH_VERDICTS =
            new java.util.concurrent.ConcurrentHashMap<>();

    /**
     * Recorded by RestAssuredRecordingFilter on every 401/403.
     *
     * <p>Folded into the digest so the auth question is answered by the same
     * small file, with no shell pipeline to run -- the previous advice was a
     * bash one-liner, which is useless on Windows.</p>
     */
    public static void recordAuthVerdict(String verdict) {
        if (verdict == null || verdict.isEmpty()) {
            return;
        }
        AUTH_VERDICTS.merge(verdict, 1, Integer::sum);
    }

    private static final Pattern[] MASKS = {
        Pattern.compile("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
                + "[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"),
        Pattern.compile("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+"),
        Pattern.compile("\\b\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}\\S*"),
        Pattern.compile("\\b\\d{5,}\\b"),
        Pattern.compile("\\bwww\\.[A-Za-z0-9.-]+"),
    };

    private static String mask(String s) {
        String out = s;
        for (Pattern p : MASKS) {
            out = p.matcher(out).replaceAll("<*>");
        }
        return out;
    }

    /** First meaningful line of the failure, masked. */
    private static String signature(Throwable t) {
        if (t == null) return "unknown";
        String msg = t.getMessage() == null ? "" : t.getMessage().trim();
        String first = "";
        for (String line : msg.split("\r?\n")) {
            String s = line.trim();
            if (s.isEmpty() || s.equals("The following asserts failed:")) continue;
            first = s;
            break;
        }
        if (first.isEmpty()) first = t.getClass().getSimpleName();
        if (first.length() > 180) first = first.substring(0, 180) + "...";
        return t.getClass().getSimpleName() + " | " + mask(first);
    }

    private static String caseIdOf(ITestResult r) {
        Object[] params = r.getParameters();
        if (params != null && params.length > 0 && params[0] instanceof Map) {
            Object v = ((Map<?, ?>) params[0]).get("test_case_id");
            if (v != null && !v.toString().isEmpty()) return v.toString();
        }
        return "-";
    }

    @Override
    public void onTestFailure(ITestResult result) {
        String cls = result.getTestClass().getRealClass().getSimpleName();
        String key = cls + "#" + result.getName() + "#" + caseIdOf(result);
        Throwable t = result.getThrowable();
        int asserts = 0;
        if (t != null && t.getMessage() != null) {
            Matcher m = Pattern.compile("(?m)^\\s+[A-Za-z]").matcher(t.getMessage());
            while (m.find()) asserts++;
        }
        FAILURES.put(key, new String[] {
            signature(t), cls, result.getName(), caseIdOf(result),
            String.valueOf(Math.max(asserts, 1)),
        });
    }

    @Override
    public void onFinish(ITestContext context) {
        Map<String, List<String[]>> bySig = new LinkedHashMap<>();
        for (String[] f : FAILURES.values()) {
            bySig.computeIfAbsent(f[0], k -> new ArrayList<>()).add(f);
        }
        List<Map.Entry<String, List<String[]>>> groups =
                new ArrayList<>(bySig.entrySet());
        groups.sort(Comparator.comparingInt(
                (Map.Entry<String, List<String[]>> e) -> e.getValue().size()).reversed());

        Path out = Paths.get("target", "failure-digest.txt");
        try {
            Files.createDirectories(out.getParent());
        } catch (IOException ignored) {
            // fall through -- the writer below reports the real problem
        }
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(
                out, StandardCharsets.UTF_8))) {
            w.printf("FAILURE DIGEST -- %s%n", context.getName());
            w.printf("unique failing (test, row) pairs: %d   distinct signatures: %d%n",
                    FAILURES.size(), groups.size());
            w.println("(retries collapsed; ids/emails/domains/dates masked as <*>)");
            w.println();
            if (!AUTH_VERDICTS.isEmpty()) {
                w.println("== auth rejections (401/403), by cause ==");
                w.println("   NO-TOKEN-SENT      -> upstream extract was empty "
                        + "(dataflow/converter bug)");
                w.println("   TOKEN-SENT-BUT-REJECTED -> token was real and refused "
                        + "(expired / audience / throttled)");
                AUTH_VERDICTS.entrySet().stream()
                        .sorted((a, b) -> b.getValue() - a.getValue())
                        .forEach(e -> w.printf("  %6d  %s%n", e.getValue(), e.getKey()));
                w.println();
            }
            w.println("== signatures, most frequent first ==");
            int n = 0;
            for (Map.Entry<String, List<String[]>> g : groups) {
                n++;
                w.printf("%n[%d] %d failure(s)  %s%n", n, g.getValue().size(), g.getKey());
                int shown = 0;
                for (String[] f : g.getValue()) {
                    if (shown++ == 6) {
                        w.printf("      ... and %d more%n", g.getValue().size() - 6);
                        break;
                    }
                    w.printf("      %s.%s  [%s]  (%s assert(s))%n",
                            f[1], f[2], f[3], f[4]);
                }
            }
            w.println();
            w.println("== every failing (test, row), one line each ==");
            for (String[] f : FAILURES.values()) {
                w.printf("%s.%s\t%s\t%s%n", f[1], f[2], f[3], f[0]);
            }
        } catch (IOException e) {
            System.out.println("[failure-digest] could not write " + out + ": " + e);
            return;
        }
        System.out.println();
        System.out.println("[failure-digest] " + FAILURES.size()
                + " unique failures across " + groups.size()
                + " signature(s) -> " + out.toAbsolutePath());
        System.out.println("[failure-digest] share THIS file, not the full log.");
        if (!AUTH_VERDICTS.isEmpty()) {
            System.out.println("[failure-digest] auth rejections by cause:");
            AUTH_VERDICTS.entrySet().stream()
                    .sorted((a, b) -> b.getValue() - a.getValue())
                    .forEach(e -> System.out.printf("   %6d  %s%n",
                            e.getValue(), e.getKey()));
        }
        for (int i = 0; i < Math.min(5, groups.size()); i++) {
            System.out.printf("   %4d x  %s%n",
                    groups.get(i).getValue().size(), groups.get(i).getKey());
        }
    }
}
