package com.hi.api.reporting;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

/**
 * Auto-generated by ra_converter. Writes a SMALL, shareable failure digest.
 *
 * <p>A full regression log is tens of MB -- too big to attach, and the
 * interesting part is a handful of distinct causes repeated hundreds of
 * times. This listener writes target/failure-digest.txt: failures
 * GROUPED by signature, counts first, a few example test-case ids each.
 * Typically a few KB.</p>
 *
 * <p>Retries are collapsed. The retry analyzer runs a failing method up to
 * 3 times, so a raw log shows each failure three times; the digest keys on
 * class#method#test_case_id and keeps one entry.</p>
 *
 * <p>The signature is the assertion/exception text with volatile parts
 * masked -- ids, emails, domains, uuids, timestamps -- so the same defect
 * across 60 rows collapses to one line instead of 60.</p>
 */
public class FailureDigestListener implements ITestListener {

    /**
     * Written from EVERY test thread -- the suite runs parallel="classes".
     * A plain LinkedHashMap here is a genuine race: entries get lost, and a
     * HashMap resized concurrently can spin. Synchronised rather than a
     * ConcurrentHashMap so insertion order survives for the per-failure
     * listing; onFinish snapshots under the same lock before iterating.
     */
    private static final Map<String, String[]> FAILURES =
            java.util.Collections.synchronizedMap(new LinkedHashMap<>());

    private static Map<String, Integer> authVerdicts() {
        return com.hi.api.rest.utilities.AuthDiagnostics.snapshot();
    }

    /**
     * Delegates to {@link com.hi.api.rest.utilities.ResponseMasking}.
     *
     * <p>The masks used to live here and matched {@code www.host} only, so a
     * bare {@code customer.com} in an assertion message reached the digest
     * unmasked. Now that response BODIES are quoted too, the shared masker
     * (UUID, email, timestamp, JWT, ANY hostname, long digit runs) is the one
     * place to fix a leak.</p>
     */
    private static String mask(String s) {
        return com.hi.api.rest.utilities.ResponseMasking.mask(s);
    }

    /** First meaningful line of the failure, masked. */
    private static String signature(Throwable t) {
        if (t == null) return "unknown";
        String msg = t.getMessage() == null ? "" : t.getMessage().trim();
        String first = "";
        for (String line : msg.split("\r?\n")) {
            String s = line.trim();
            if (s.isEmpty() || s.equals("The following asserts failed:")) continue;
            first = s;
            break;
        }
        if (first.isEmpty()) first = t.getClass().getSimpleName();
        if (first.length() > 180) first = first.substring(0, 180) + "...";
        return t.getClass().getSimpleName() + " | " + mask(first) + rootCauseSuffix(t);
    }

    /**
     * A wrapper like "RestStep X exchange failed" says where, not why: the
     * why is the cause chain (SocketTimeoutException: Read timed out,
     * SSLHandshakeException, JSON parse ...). Without it 17 identical
     * signatures in one digest gave nothing to act on. Appends the deepest
     * cause as {@code <- Class: first line}, masked like everything else.
     */
    private static String rootCauseSuffix(Throwable t) {
        Throwable root = t;
        int hops = 0;
        while (root.getCause() != null && root.getCause() != root && hops++ < 12) {
            root = root.getCause();
        }
        if (root == t) return "";
        String msg = root.getMessage() == null ? "" : root.getMessage().trim();
        String first = msg.split("\r?\n", 2)[0].trim();
        if (first.length() > 120) first = first.substring(0, 120) + "...";
        return " <- " + root.getClass().getSimpleName()
                + (first.isEmpty() ? "" : ": " + mask(first));
    }

    private static final char QUOTE_CHAR = (char) 34;
    private static final String QUOTE = String.valueOf(QUOTE_CHAR);

    /**
     * Pair each field the server REJECTED with the value we SENT for it.
     *
     * <p>The server names the field ({@code "fields":["startDate"]}) and
     * we hold the request, so the one line that actually diagnoses the
     * failure can be assembled rather than asked for. Looks in the JSON
     * body first, then the query string, since a rejected parameter can
     * live in either.</p>
     *
     * <p>Scanned with indexOf rather than a regex on purpose: this class
     * is emitted from a Python template, and a regex here has to survive
     * an f-string, a Python literal and javac. The first attempt did not
     * -- it shipped a Pattern.compile whose backslashes had been eaten,
     * and a replace() whose quote literal had collapsed. Neither
     * compiled, and the comment describing it broke the template too.</p>
     *
     * <p>Best-effort: a field it cannot find is reported as such, and a
     * miss costs nothing.</p>
     */
    private static String offendingFields(String serverBody, String request,
                                          String url) {
        if (serverBody == null || serverBody.isEmpty()) {
            return "";
        }
        java.util.LinkedHashSet<String> names = new java.util.LinkedHashSet<>();
        String marker = QUOTE + "fields" + QUOTE;
        int at = serverBody.indexOf(marker);
        while (at >= 0) {
            int open = serverBody.indexOf('[', at);
            int close = open < 0 ? -1 : serverBody.indexOf(']', open);
            if (open < 0 || close < 0) {
                break;
            }
            for (String rawName : serverBody.substring(open + 1, close).split(",")) {
                String n = rawName.replace(QUOTE, "").trim();
                int dot = n.lastIndexOf('.');      // roomTypes.roomTypeCode
                if (dot >= 0 && dot + 1 < n.length()) {
                    n = n.substring(dot + 1);
                }
                if (!n.isEmpty()) {
                    names.add(n);
                }
            }
            at = serverBody.indexOf(marker, close);
        }
        if (names.isEmpty()) {
            return "";
        }
        StringBuilder out = new StringBuilder();
        for (String n : names) {
            String v = jsonValueOf(request, n);
            if (v == null) {
                v = queryValueOf(url, n);
            }
            if (out.length() > 0) {
                out.append("   ");
            }
            out.append(n).append('=');
            if (v == null) {
                out.append("<not in the request>");
            } else {
                // The note goes AFTER the closing quote. Inside it, the
                // first real digest to carry one read
                //   arrivalDate="   <-- empty: resolved to nothing"
                // which reads as though the sentence were the value.
                out.append(QUOTE).append(fieldValue(n, v)).append(QUOTE);
                out.append(whyNotAValue(v));
            }
        }
        return out.toString();
    }

    /**
     * The offending value, shown rather than masked.
     *
     * <p>mask() replaces a date with {@code <*>}, which is right for the
     * rest of the digest and exactly wrong here: the first value this
     * line ever had to explain WAS a date -- an Excel cell arriving as
     * {@code 2026-12-17 00:00:00} -- and a masked one says nothing.
     * A field the server rejected is by definition the value to look
     * at.</p>
     *
     * <p>Credential-shaped field names are redacted anyway. A digest is
     * pasted into chats and tickets, and no diagnostic need justifies
     * printing a secret; the request body beside it is redacted at the
     * source for the same reason.</p>
     */
    private static String fieldValue(String name, String value) {
        String n = name == null ? "" : name.toLowerCase(java.util.Locale.ROOT);
        for (String hint : new String[] {"password", "passwd", "secret",
                "token", "authorization", "apikey", "api_key", "assertion",
                "credential"}) {
            if (n.contains(hint)) {
                return "<redacted>";
            }
        }
        String v = value.replace(chr10(), ' ').replace(chr13(), ' ');
        if (v.length() > 80) {
            v = v.substring(0, 80) + " ...(capped)";
        }
        return v;
    }

    /**
     * Say when a value is not data at all but a substitution that failed.
     *
     * <p>{@code startDate="null"} reads like data, and the server's
     * complaint about it reads like a data problem. It is neither: `null`
     * is the literal RestUtilities substitutes when nothing resolved the
     * placeholder, so the fault is upstream of the request and no amount
     * of staring at the date will show it. A `#key#` that survived to the
     * wire is the same story one step earlier.</p>
     *
     * <p>Worth a few characters because the alternative was a whole run:
     * the digest named the field, the field looked plausible, and the
     * real question -- why did nothing fill it -- was never asked.</p>
     */
    private static String whyNotAValue(String v) {
        if ("null".equals(v)) {
            return "   <-- unresolved placeholder: nothing supplied this"
                    + " field, `null` is the substitution fallback";
        }
        if (v.indexOf('#') >= 0 || v.startsWith("${")) {
            return "   <-- unexpanded reference reached the wire";
        }
        if (v.isEmpty()) {
            return "   <-- empty: resolved to nothing";
        }
        return "";
    }

    private static char chr10() {
        return (char) 10;
    }

    private static char chr13() {
        return (char) 13;
    }

    /** First JSON scalar for {@code name} in {@code json}, or null. */
    private static String jsonValueOf(String json, String name) {
        if (json == null || json.isEmpty() || name == null) {
            return null;
        }
        int k = json.indexOf(QUOTE + name + QUOTE);
        if (k < 0) {
            return null;
        }
        int colon = json.indexOf(':', k + name.length() + 2);
        if (colon < 0) {
            return null;
        }
        int i = colon + 1;
        while (i < json.length() && Character.isWhitespace(json.charAt(i))) {
            i++;
        }
        if (i >= json.length()) {
            return null;
        }
        if (json.charAt(i) == QUOTE_CHAR) {
            int end = json.indexOf(QUOTE_CHAR, i + 1);
            return end < 0 ? null : json.substring(i + 1, end);
        }
        char open = json.charAt(i);
        if (open == '[' || open == '{') {
            // An ARRAY or OBJECT. Scanning for the next delimiter returns
            // the single character "[", which is how a real digest came to
            // say  inventoryPeriods="["  about a field the server had
            // rejected. What the reader needs is the extent: whether we
            // sent nothing, one entry, or ten.
            return spanOf(json, i, open);
        }
        int end = i;
        while (end < json.length()
                && ",}] ".indexOf(json.charAt(end)) < 0) {
            end++;
        }
        return json.substring(i, end);
    }

    /**
     * The bracketed value starting at {@code i}, summarised.
     *
     * <p>Balanced scan, ignoring brackets inside strings, so a nested
     * array does not end the span early. An empty one says so plainly --
     * "the field was present and empty" is a different diagnosis from
     * "the field was absent", and the server's complaint rarely
     * distinguishes them.</p>
     */
    private static String spanOf(String json, int i, char open) {
        char close = (open == '[') ? ']' : '}';
        int depth = 0;
        boolean inStr = false;
        for (int k = i; k < json.length(); k++) {
            char c = json.charAt(k);
            if (inStr) {
                if (c == QUOTE_CHAR) {
                    inStr = false;
                }
                continue;
            }
            if (c == QUOTE_CHAR) {
                inStr = true;
            } else if (c == open) {
                depth++;
            } else if (c == close) {
                depth--;
                if (depth == 0) {
                    String body = json.substring(i, k + 1);
                    String inner = body.substring(1, body.length() - 1).trim();
                    if (inner.isEmpty()) {
                        return open == '[' ? "[] (empty array)"
                                           : "{} (empty object)";
                    }
                    return body.length() <= 80 ? body
                            : body.substring(0, 80) + " ...(capped)";
                }
            }
        }
        return String.valueOf(open) + "...(unterminated)";
    }

    /** Value of query parameter {@code name} in {@code url}, or null. */
    private static String queryValueOf(String url, String name) {
        if (url == null || name == null || url.indexOf('?') < 0) {
            return null;
        }
        String q = url.substring(url.indexOf('?') + 1);
        for (String pair : q.split("&")) {
            int eq = pair.indexOf('=');
            if (eq > 0 && pair.substring(0, eq).equals(name)) {
                return pair.substring(eq + 1);
            }
        }
        return null;
    }

    private static String caseIdOf(ITestResult r) {
        Object[] params = r.getParameters();
        if (params != null && params.length > 0 && params[0] instanceof Map) {
            Object v = ((Map<?, ?>) params[0]).get("test_case_id");
            if (v != null && !v.toString().isEmpty()) return v.toString();
        }
        return "-";
    }

    @Override
    public void onTestStart(ITestResult result) {
        com.hi.api.rest.utilities.StepOutcomes.reset();
    }

    @Override
    public void onTestFailure(ITestResult result) {
        String cls = result.getTestClass().getRealClass().getSimpleName();
        String key = cls + "#" + result.getName() + "#" + caseIdOf(result);
        Throwable t = result.getThrowable();
        int asserts = 0;
        if (t != null && t.getMessage() != null) {
            Matcher m = Pattern.compile("(?m)^\\s+[A-Za-z]").matcher(t.getMessage());
            while (m.find()) asserts++;
        }
        // FIRST non-2xx, not last: the earliest failed call is the one that
        // did not mint the id everything after it needed. Its body is kept
        // (already capped by RestStep) so the digest can quote the server's
        // own reason instead of the framework's symptom. Masked again here:
        // cheap, and it means a body from any producer is safe to print.
        String upstream = com.hi.api.rest.utilities.StepOutcomes.firstFailure();
        String body = com.hi.api.rest.utilities.StepOutcomes.firstFailureBody();
        // The REQUEST behind that failure. Quoting the server's complaint
        // without the value that caused it is half a diagnosis: "Invalid
        // JSON Parameter Value, fields:[startDate]" cost a round trip to
        // learn that startDate was `2026-12-17 00:00:00`.
        String url = com.hi.api.rest.utilities.StepOutcomes.firstFailureUrl();
        String req = com.hi.api.rest.utilities.StepOutcomes.firstFailureRequest();
        FAILURES.put(key, new String[] {
            signature(t), cls, result.getName(), caseIdOf(result),
            String.valueOf(Math.max(asserts, 1)),
            upstream == null ? "" : upstream,
            body == null ? "" : mask(body),
            url == null ? "" : mask(url),
            req == null ? "" : mask(req),
            // What WE sent for each field the server named. The server
            // says which field it rejected; this says what was in it.
            offendingFields(body, req, url),
        });
    }

    private static final java.util.concurrent.atomic.AtomicBoolean WRITTEN =
            new java.util.concurrent.atomic.AtomicBoolean(false);

    /**
     * Say how many checks did not run.
     *
     * <p>Skipping an assertion whose expected value is still a
     * placeholder is right -- it could only ever be false. But the run
     * then reports PASSED for a test that verified almost nothing, and
     * until now the only trace was 246 separate WARN lines in a 20 MB
     * log. A count next to the result is the difference between "green"
     * and "green, having checked 246 fewer things than it looks like".</p>
     */
    private void reportSkippedChecks() {
        try {
            int total = com.hi.api.rest.utilities.ResponseAsserts.skippedTotal();
            if (total <= 0) {
                // Say so rather than stay silent. One full run logged 56
                // `[assert SKIPPED]` lines from ResponseAsserts -- all of
                // which call countSkip, all of them BEFORE this listener
                // ran -- and this method still saw zero, then printed
                // nothing. An absent line is indistinguishable from "the
                // listener never fired", so there was no way to tell which
                // half was broken. Resets, duplicate classes, an untracked
                // copy and classloader isolation were all ruled out; this
                // line is the evidence the next run needs.
                System.out.println("[digest] 0 check(s) recorded as skipped. "
                        + "If the run logged `[assert SKIPPED]` lines, the "
                        + "counter and this listener are not seeing the same "
                        + "ResponseAsserts class.");
                return;
            }
            StringBuilder sb = new StringBuilder();
            sb.append("[digest] ").append(total)
              .append(" check(s) did NOT run. A passing test here verified "
                      + "less than its name suggests:");
            com.hi.api.rest.utilities.ResponseAsserts.skippedCounts()
                    .forEach((reason, n) ->
                            sb.append("\n           ").append(n)
                              .append(" x ").append(reason));
            System.out.println(sb.toString());
        } catch (RuntimeException e) {
            // A reporting aid must never be the reason a suite fails.
            System.out.println("[digest] skipped-check summary "
                               + "unavailable: " + e);
        }
    }

    @Override
    public void onFinish(ITestContext context) {
        // Registered BOTH in the generated suite XML and via
        // META-INF/services, because a `-Dtest=` run bypasses the suite XML
        // entirely -- which is why a targeted run produced no digest at all.
        // Belt and braces means onFinish can fire twice; write once.
        if (!WRITTEN.compareAndSet(false, true)) {
            return;
        }
        reportSkippedChecks();
        List<String[]> all;
        synchronized (FAILURES) {
            all = new ArrayList<>(FAILURES.values());
        }
        Map<String, List<String[]>> bySig = new LinkedHashMap<>();
        for (String[] f : all) {
            bySig.computeIfAbsent(f[0], k -> new ArrayList<>()).add(f);
        }
        List<Map.Entry<String, List<String[]>>> groups =
                new ArrayList<>(bySig.entrySet());
        groups.sort(Comparator.comparingInt(
                (Map.Entry<String, List<String[]>> e) -> e.getValue().size()).reversed());

        Path out = Paths.get("target", "failure-digest.txt");
        try {
            Files.createDirectories(out.getParent());
        } catch (IOException ignored) {
            // fall through -- the writer below reports the real problem
        }
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(
                out, StandardCharsets.UTF_8))) {
            w.printf("FAILURE DIGEST -- %s%n", context.getName());
            w.printf("unique failing (test, row) pairs: %d   distinct signatures: %d%n",
                    all.size(), groups.size());
            w.println("(retries collapsed; ids/emails/domains/dates masked as <*>)");
            w.println("digest v4 -- `we sent:` shows OUR value for each field the"
                    + " server named, UNMASKED (a masked value explains"
                    + " nothing; credential-shaped field names are redacted),"
                    + " plus"
                    + " `url:` and the redacted `request:` behind"
                    + " the FIRST non-2xx. v3 added `server said:`, the FIRST"
                    + " failed call rather than the last, and auth verdicts"
                    + " OBSERVED on the wire vs INFERRED from ctx");
            w.println();
            w.println("== auth rejections (401/403), by cause ==");
            if (authVerdicts().isEmpty()) {
                w.println("  none observed in this run");
                w.println();
            } else {
                w.println("   Two producers, NOT equivalent:");
                w.println("   header:*             OBSERVED -- what the Authorization"
                        + " header actually carried on the wire");
                w.println("                        (RestAssuredRecordingFilter)");
                w.println("   TOKEN-*-IN-CTX (len) INFERRED -- what ctx held when the"
                        + " step was built (RestStep); a token in ctx");
                w.println("                        can still be absent from the"
                        + " request if the template never referenced it");
                w.println("   NO-TOKEN-SENT        -> upstream extract was empty "
                        + "(dataflow/converter bug)");
                w.println("   TOKEN-SENT-BUT-REJECTED -> token was real and refused "
                        + "(expired / audience / throttled)");
                authVerdicts().entrySet().stream()
                        .forEach(e -> w.printf("  %6d  %s%n", e.getValue(), e.getKey()));
                w.println();
            }
            w.println("== signatures, most frequent first ==");
            int n = 0;
            for (Map.Entry<String, List<String[]>> g : groups) {
                n++;
                w.printf("%n[%d] %d failure(s)  %s%n", n, g.getValue().size(), g.getKey());
                int shown = 0;
                for (String[] f : g.getValue()) {
                    if (shown++ == 6) {
                        w.printf("      ... and %d more%n", g.getValue().size() - 6);
                        break;
                    }
                    w.printf("      %s.%s  [%s]  (%s assert(s))%s%n",
                            f[1], f[2], f[3], f[4],
                            f.length > 5 && !f[5].isEmpty()
                                    ? "   first bad call: " + f[5] : "");
                    if (f.length > 6 && !f[6].isEmpty()) {
                        w.printf("         server said: %s%n", f[6]);
                    }
                    if (f.length > 9 && !f[9].isEmpty()) {
                        w.printf("         we sent    : %s%n", f[9]);
                    }
                    if (f.length > 7 && !f[7].isEmpty()) {
                        w.printf("         url        : %s%n", f[7]);
                    }
                    if (f.length > 8 && !f[8].isEmpty()) {
                        w.printf("         request    : %s%n",
                                f[8].length() > 400
                                        ? f[8].substring(0, 400) + " ...(capped)"
                                        : f[8]);
                    }
                }
            }
            w.println();
            w.println("== first failing call behind each failure ==");
            w.println("   (a broken path or a missing id is usually a SYMPTOM;");
            w.println("    this is the earliest non-2xx seen in that test)");
            Map<String, Integer> upstream = new LinkedHashMap<>();
            Map<String, String> firstBody = new LinkedHashMap<>();
            int clean = 0;
            for (String[] f : all) {
                if (f.length > 5 && !f[5].isEmpty()) {
                    upstream.merge(f[5], 1, Integer::sum);
                    if (f.length > 6 && !f[6].isEmpty()) {
                        firstBody.putIfAbsent(f[5], f[6]);
                    }
                } else {
                    clean++;
                }
            }
            upstream.entrySet().stream()
                    .sorted((a, b) -> b.getValue() - a.getValue())
                    .forEach(e -> {
                        w.printf("  %6d  %s%n", e.getValue(), e.getKey());
                        String b = firstBody.get(e.getKey());
                        if (b != null) {
                            w.printf("          server said: %s%n", b);
                        }
                    });
            if (clean > 0) {
                w.printf("  %6d  (no failed call -- assertion-only failure)%n", clean);
            }
            w.println();
            w.println("== every failing (test, row), one line each ==");
            for (String[] f : all) {
                w.printf("%s.%s\t%s\t%s%n", f[1], f[2], f[3], f[0]);
            }
        } catch (IOException e) {
            System.out.println("[failure-digest] could not write " + out + ": " + e);
            return;
        }
        System.out.println();
        System.out.println("[failure-digest] " + all.size()
                + " unique failures across " + groups.size()
                + " signature(s) -> " + out.toAbsolutePath());
        System.out.println("[failure-digest] share THIS file, not the full log.");
        if (!authVerdicts().isEmpty()) {
            System.out.println("[failure-digest] auth rejections by cause:");
            authVerdicts().entrySet().stream()
                    .forEach(e -> System.out.printf("   %6d  %s%n",
                            e.getValue(), e.getKey()));
        }
        for (int i = 0; i < Math.min(5, groups.size()); i++) {
            System.out.printf("   %4d x  %s%n",
                    groups.get(i).getValue().size(), groups.get(i).getKey());
        }
    }
}
