package com.hi.api.reporting;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

/**
 * Auto-generated by ra_converter. Writes a SMALL, shareable failure digest.
 *
 * <p>A full regression log is tens of MB -- too big to attach, and the
 * interesting part is a handful of distinct causes repeated hundreds of
 * times. This listener writes target/failure-digest.txt: failures
 * GROUPED by signature, counts first, a few example test-case ids each.
 * Typically a few KB.</p>
 *
 * <p>Retries are collapsed. The retry analyzer runs a failing method up to
 * 3 times, so a raw log shows each failure three times; the digest keys on
 * class#method#test_case_id and keeps one entry.</p>
 *
 * <p>The signature is the assertion/exception text with volatile parts
 * masked -- ids, emails, domains, uuids, timestamps -- so the same defect
 * across 60 rows collapses to one line instead of 60.</p>
 */
public class FailureDigestListener implements ITestListener {

    /**
     * Written from EVERY test thread -- the suite runs parallel="classes".
     * A plain LinkedHashMap here is a genuine race: entries get lost, and a
     * HashMap resized concurrently can spin. Synchronised rather than a
     * ConcurrentHashMap so insertion order survives for the per-failure
     * listing; onFinish snapshots under the same lock before iterating.
     */
    private static final Map<String, String[]> FAILURES =
            java.util.Collections.synchronizedMap(new LinkedHashMap<>());

    private static Map<String, Integer> authVerdicts() {
        return com.hi.api.rest.utilities.AuthDiagnostics.snapshot();
    }

    /**
     * Delegates to {@link com.hi.api.rest.utilities.ResponseMasking}.
     *
     * <p>The masks used to live here and matched {@code www.host} only, so a
     * bare {@code customer.com} in an assertion message reached the digest
     * unmasked. Now that response BODIES are quoted too, the shared masker
     * (UUID, email, timestamp, JWT, ANY hostname, long digit runs) is the one
     * place to fix a leak.</p>
     */
    private static String mask(String s) {
        return com.hi.api.rest.utilities.ResponseMasking.mask(s);
    }

    /** First meaningful line of the failure, masked. */
    private static String signature(Throwable t) {
        if (t == null) return "unknown";
        String msg = t.getMessage() == null ? "" : t.getMessage().trim();
        String first = "";
        for (String line : msg.split("\r?\n")) {
            String s = line.trim();
            if (s.isEmpty() || s.equals("The following asserts failed:")) continue;
            first = s;
            break;
        }
        if (first.isEmpty()) first = t.getClass().getSimpleName();
        if (first.length() > 180) first = first.substring(0, 180) + "...";
        return t.getClass().getSimpleName() + " | " + mask(first) + rootCauseSuffix(t);
    }

    /**
     * A wrapper like "RestStep X exchange failed" says where, not why: the
     * why is the cause chain (SocketTimeoutException: Read timed out,
     * SSLHandshakeException, JSON parse ...). Without it 17 identical
     * signatures in one digest gave nothing to act on. Appends the deepest
     * cause as {@code <- Class: first line}, masked like everything else.
     */
    private static String rootCauseSuffix(Throwable t) {
        Throwable root = t;
        int hops = 0;
        while (root.getCause() != null && root.getCause() != root && hops++ < 12) {
            root = root.getCause();
        }
        if (root == t) return "";
        String msg = root.getMessage() == null ? "" : root.getMessage().trim();
        String first = msg.split("\r?\n", 2)[0].trim();
        if (first.length() > 120) first = first.substring(0, 120) + "...";
        return " <- " + root.getClass().getSimpleName()
                + (first.isEmpty() ? "" : ": " + mask(first));
    }

    private static String caseIdOf(ITestResult r) {
        Object[] params = r.getParameters();
        if (params != null && params.length > 0 && params[0] instanceof Map) {
            Object v = ((Map<?, ?>) params[0]).get("test_case_id");
            if (v != null && !v.toString().isEmpty()) return v.toString();
        }
        return "-";
    }

    @Override
    public void onTestStart(ITestResult result) {
        com.hi.api.rest.utilities.StepOutcomes.reset();
    }

    @Override
    public void onTestFailure(ITestResult result) {
        String cls = result.getTestClass().getRealClass().getSimpleName();
        String key = cls + "#" + result.getName() + "#" + caseIdOf(result);
        Throwable t = result.getThrowable();
        int asserts = 0;
        if (t != null && t.getMessage() != null) {
            Matcher m = Pattern.compile("(?m)^\\s+[A-Za-z]").matcher(t.getMessage());
            while (m.find()) asserts++;
        }
        // FIRST non-2xx, not last: the earliest failed call is the one that
        // did not mint the id everything after it needed. Its body is kept
        // (already capped by RestStep) so the digest can quote the server's
        // own reason instead of the framework's symptom. Masked again here:
        // cheap, and it means a body from any producer is safe to print.
        String upstream = com.hi.api.rest.utilities.StepOutcomes.firstFailure();
        String body = com.hi.api.rest.utilities.StepOutcomes.firstFailureBody();
        FAILURES.put(key, new String[] {
            signature(t), cls, result.getName(), caseIdOf(result),
            String.valueOf(Math.max(asserts, 1)),
            upstream == null ? "" : upstream,
            body == null ? "" : mask(body),
        });
    }

    private static final java.util.concurrent.atomic.AtomicBoolean WRITTEN =
            new java.util.concurrent.atomic.AtomicBoolean(false);

    @Override
    public void onFinish(ITestContext context) {
        // Registered BOTH in the generated suite XML and via
        // META-INF/services, because a `-Dtest=` run bypasses the suite XML
        // entirely -- which is why a targeted run produced no digest at all.
        // Belt and braces means onFinish can fire twice; write once.
        if (!WRITTEN.compareAndSet(false, true)) {
            return;
        }
        List<String[]> all;
        synchronized (FAILURES) {
            all = new ArrayList<>(FAILURES.values());
        }
        Map<String, List<String[]>> bySig = new LinkedHashMap<>();
        for (String[] f : all) {
            bySig.computeIfAbsent(f[0], k -> new ArrayList<>()).add(f);
        }
        List<Map.Entry<String, List<String[]>>> groups =
                new ArrayList<>(bySig.entrySet());
        groups.sort(Comparator.comparingInt(
                (Map.Entry<String, List<String[]>> e) -> e.getValue().size()).reversed());

        Path out = Paths.get("target", "failure-digest.txt");
        try {
            Files.createDirectories(out.getParent());
        } catch (IOException ignored) {
            // fall through -- the writer below reports the real problem
        }
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(
                out, StandardCharsets.UTF_8))) {
            w.printf("FAILURE DIGEST -- %s%n", context.getName());
            w.printf("unique failing (test, row) pairs: %d   distinct signatures: %d%n",
                    all.size(), groups.size());
            w.println("(retries collapsed; ids/emails/domains/dates masked as <*>)");
            w.println("digest v3 -- adds `server said:` (masked body of the FIRST"
                    + " non-2xx), records the FIRST failed call rather than the"
                    + " last, and separates auth verdicts OBSERVED on the wire"
                    + " from those INFERRED from ctx");
            w.println();
            w.println("== auth rejections (401/403), by cause ==");
            if (authVerdicts().isEmpty()) {
                w.println("  none observed in this run");
                w.println();
            } else {
                w.println("   Two producers, NOT equivalent:");
                w.println("   header:*             OBSERVED -- what the Authorization"
                        + " header actually carried on the wire");
                w.println("                        (RestAssuredRecordingFilter)");
                w.println("   TOKEN-*-IN-CTX (len) INFERRED -- what ctx held when the"
                        + " step was built (RestStep); a token in ctx");
                w.println("                        can still be absent from the"
                        + " request if the template never referenced it");
                w.println("   NO-TOKEN-SENT        -> upstream extract was empty "
                        + "(dataflow/converter bug)");
                w.println("   TOKEN-SENT-BUT-REJECTED -> token was real and refused "
                        + "(expired / audience / throttled)");
                authVerdicts().entrySet().stream()
                        .forEach(e -> w.printf("  %6d  %s%n", e.getValue(), e.getKey()));
                w.println();
            }
            w.println("== signatures, most frequent first ==");
            int n = 0;
            for (Map.Entry<String, List<String[]>> g : groups) {
                n++;
                w.printf("%n[%d] %d failure(s)  %s%n", n, g.getValue().size(), g.getKey());
                int shown = 0;
                for (String[] f : g.getValue()) {
                    if (shown++ == 6) {
                        w.printf("      ... and %d more%n", g.getValue().size() - 6);
                        break;
                    }
                    w.printf("      %s.%s  [%s]  (%s assert(s))%s%n",
                            f[1], f[2], f[3], f[4],
                            f.length > 5 && !f[5].isEmpty()
                                    ? "   first bad call: " + f[5] : "");
                    if (f.length > 6 && !f[6].isEmpty()) {
                        w.printf("         server said: %s%n", f[6]);
                    }
                }
            }
            w.println();
            w.println("== first failing call behind each failure ==");
            w.println("   (a broken path or a missing id is usually a SYMPTOM;");
            w.println("    this is the earliest non-2xx seen in that test)");
            Map<String, Integer> upstream = new LinkedHashMap<>();
            Map<String, String> firstBody = new LinkedHashMap<>();
            int clean = 0;
            for (String[] f : all) {
                if (f.length > 5 && !f[5].isEmpty()) {
                    upstream.merge(f[5], 1, Integer::sum);
                    if (f.length > 6 && !f[6].isEmpty()) {
                        firstBody.putIfAbsent(f[5], f[6]);
                    }
                } else {
                    clean++;
                }
            }
            upstream.entrySet().stream()
                    .sorted((a, b) -> b.getValue() - a.getValue())
                    .forEach(e -> {
                        w.printf("  %6d  %s%n", e.getValue(), e.getKey());
                        String b = firstBody.get(e.getKey());
                        if (b != null) {
                            w.printf("          server said: %s%n", b);
                        }
                    });
            if (clean > 0) {
                w.printf("  %6d  (no failed call -- assertion-only failure)%n", clean);
            }
            w.println();
            w.println("== every failing (test, row), one line each ==");
            for (String[] f : all) {
                w.printf("%s.%s\t%s\t%s%n", f[1], f[2], f[3], f[0]);
            }
        } catch (IOException e) {
            System.out.println("[failure-digest] could not write " + out + ": " + e);
            return;
        }
        System.out.println();
        System.out.println("[failure-digest] " + all.size()
                + " unique failures across " + groups.size()
                + " signature(s) -> " + out.toAbsolutePath());
        System.out.println("[failure-digest] share THIS file, not the full log.");
        if (!authVerdicts().isEmpty()) {
            System.out.println("[failure-digest] auth rejections by cause:");
            authVerdicts().entrySet().stream()
                    .forEach(e -> System.out.printf("   %6d  %s%n",
                            e.getValue(), e.getKey()));
        }
        for (int i = 0; i < Math.min(5, groups.size()); i++) {
            System.out.printf("   %4d x  %s%n",
                    groups.get(i).getValue().size(), groups.get(i).getKey());
        }
    }
}
