"""A multi-code `Valid HTTP Status Codes` assertion is asserted ONCE, and
the digest stops counting it as skipped.

ReadyAPI lets an assertion list several codes (`200,201,206`). The
emitter wrote an EMPTY CSV cell for those and emitted its own inline
`Set.of(...).contains(status)` check in the hook. RestStep, which asserts
every step's status from the cell, saw the empty cell and logged

    [status-code assert SKIPPED] step=POST_groupEvents -- no expected status
    configured (CSV column `expected_POST_groupEvents_status_code` empty)

and counted a skipped check -- 26 per run on goal3487 -- while the
inline check quietly did the work. The digest then said 26 checks did
not run. They did. The accounting was wrong, not the assertion.

Now the cell carries the list, `ResponseAsserts.statusFromStepColumn`
accepts a comma list (any listed code passes), and the inline duplicate
is a comment. One check, truthful digest, and a row can still override
with a single code.

    python tools/ra_converter/test_multi_code_status_cell.py
"""

import csv
import glob
import io
import inspect
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

sys.path.insert(0, HERE)

import ra_converter as rc  # noqa: E402


def _assertion(codes):
    a = rc.Assertion.__new__(rc.Assertion)
    a.type = "Valid HTTP Status Codes"
    a.config = {"codes": codes}
    a.name = "Valid HTTP Status Codes"
    a.disabled = False
    a.elements = []
    return a


def test_a_multi_code_assertion_fills_the_cell_with_the_list():
    assert rc._assert_default_value(_assertion("200,201,206")) == "200,201,206"
    assert rc._assert_default_value(_assertion("200, 206, 201")) == "200,206,201"


def test_a_single_code_cell_is_unchanged():
    assert rc._assert_default_value(_assertion("201")) == "201"
    assert rc._assert_default_value(_assertion("")) == "200"


def test_the_emitter_no_longer_emits_an_inline_set_check():
    """The inline check would now parse the list as one int and assert the
    first code strictly -- a 206 against `200,201,206` would fail."""
    src = inspect.getsource(rc)
    assert "validCodes_{vsid}" not in src, (
        "the inline Set.of status check must not be emitted any more")
    assert "any listed code; asserted by RestStep" in src


def test_the_generated_cells_carry_the_list():
    """Against the real CSVs, when present and generated by this converter."""
    converter_mtime = os.path.getmtime(os.path.join(HERE, "ra_converter.py"))
    checked = 0
    for f in glob.glob(os.path.join(ROOT, "src", "test", "resources", "csv",
                                    "**", "*.csv"), recursive=True):
        try:
            if os.path.getmtime(f) < converter_mtime:
                continue                   # older converter wrote it
            with io.open(f, encoding="utf-8-sig", newline="") as fh:
                rows = list(csv.reader(fh))
        except OSError:
            continue                       # Windows MAX_PATH: not evidence
        if not rows:
            continue
        for i, col in enumerate(rows[0]):
            if not (col.startswith("expected_") and col.endswith("_status_code")):
                continue
            for r in rows[1:]:
                v = (r[i] if i < len(r) else "").strip()
                if v:
                    assert re.match(r"^\d+(,\d+)*$", v), (f, col, v)
                    checked += 1
    # No assertion on `checked`: a tree with no fresh CSVs proves nothing,
    # and the unit tests above hold the rule regardless.


def test_the_hook_for_a_multi_code_step_is_a_comment_not_a_check():
    hooks = glob.glob(os.path.join(ROOT, "src", "main", "java", "com", "hi", "api",
                                   "support", "*", "cases", "*Hooks*.java"))
    converter_mtime = os.path.getmtime(os.path.join(HERE, "ra_converter.py"))
    for h in hooks:
        if os.path.getmtime(h) < converter_mtime:
            continue
        text = io.open(h, encoding="utf-8", errors="replace").read()
        assert "validCodes_" not in text, (
            os.path.basename(h) + " still carries the inline Set.of status check")


if __name__ == "__main__":
    passed = 0
    for name, fn in sorted(list(globals().items())):
        if name.startswith("test_") and callable(fn):
            fn()
            print("ok  " + name)
            passed += 1
    print("%d passed" % passed)
